services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  db:
    build: ./persistance #To execute the Dockerfile in the specified path, it handles provinces data import
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tutoring
    ports:
      - "2345:5432" #Internally to docker it's port 5432, for pgAdmin in local machine it's localhost, at port 2345

  mongo:
    image: mongo
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017" #Internally to docker it's port 27017, for compass in local machine it's localhost, at port 27017

  covidextractor:
    build: ./covid-extractor
    container_name: extractor
    depends_on:
      - broker
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: 'production'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'
      SPRING_JPA_HIBERNATE_DDL_AUTO: update


  covidaggregator:
    build: ./covid-aggregator
    container_name: aggregator
    depends_on:
      - broker
      - mongo
    ports:
      - "9090:9090"
    environment:
      SPRING_PROFILES_ACTIVE: 'production'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'